[package]
name = "Hello_Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rand = "0.8.5"
#rodio = "0.17.1"
#serde_json = "1.0.96"
#chrono = "0.4.26"